In [36]:
import pandas as pd

In [37]:
euro = pd.read_csv('Euro_2012_stats_TEAM.csv', sep = ',')

In [38]:
euro

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

1. Total/max/min number of scored goals

In [39]:
euro.Goals.mean()

4.75

In [40]:
euro.Goals.max()

12

In [41]:
euro.Goals.min()

1

2. Teams sorted by scored goals.

In [42]:
euro.groupby('Team').Goals.sum().sort_values(ascending = False)

Team
Spain                  12
Germany                10
Italy                   6
Portugal                6
England                 5
Greece                  5
Russia                  5
Sweden                  5
Croatia                 4
Czech Republic          4
Denmark                 4
France                  3
Netherlands             2
Poland                  2
Ukraine                 2
Republic of Ireland     1
Name: Goals, dtype: int64

3. Statistics  of team who scored minimum  goals

In [43]:
euro.loc[euro.Goals == euro.Goals.min()]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17

4. statistic of teams who has less than 4 yellow cards

In [65]:
euro.loc[euro["Yellow Cards"].isin(range(5))]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17

5. Teams who scored more than average number of goals.

In [27]:
euro.loc[(euro.Goals>euro.Goals.mean())].Team

3      England
5      Germany
6       Greece
7        Italy
10    Portugal
12      Russia
13       Spain
14      Sweden
Name: Team, dtype: object

6. How many not realized shot on targets each team have

In [79]:
euro["notreal"] = euro["Shots on target"] - euro["Goals"]
euro.groupby('Team').notreal.sum()

Team
Croatia                 9
Czech Republic          9
Denmark                 6
England                 6
France                 19
Germany                22
Greece                  3
Italy                  28
Netherlands            10
Poland                 13
Portugal               16
Republic of Ireland     6
Russia                  4
Spain                  30
Sweden                 12
Ukraine                 5
Name: notreal, dtype: int64

7. Persent of realizeted shot on targets

In [94]:
def realization (row):
    row["notreal"] = 1 - (int(row["notreal"]) / int(row["Shots on target"]))
    return row

euro.apply(realization, axis='columns').groupby("Team").notreal.sum().sort_values(ascending = False)

Team
Greece                 0.625000
Russia                 0.555556
England                0.454545
Denmark                0.400000
Germany                0.312500
Croatia                0.307692
Czech Republic         0.307692
Sweden                 0.294118
Spain                  0.285714
Ukraine                0.285714
Portugal               0.272727
Italy                  0.176471
Netherlands            0.166667
Republic of Ireland    0.142857
France                 0.136364
Poland                 0.133333
Name: notreal, dtype: float64

8. Headed goals to goals

In [132]:
def headgoalstogoals (row):
    row["Headed goals"] = (int(row["Headed goals"]) / int(row["Goals"]))
    return row

euro.apply(headgoalstogoals, axis='columns').groupby("Team")["Headed goals"].sum()

Team
Croatia                0.500000
Czech Republic         0.000000
Denmark                0.750000
England                0.600000
France                 0.000000
Germany                0.200000
Greece                 0.000000
Italy                  0.333333
Netherlands            0.000000
Poland                 0.500000
Portugal               0.333333
Republic of Ireland    1.000000
Russia                 0.200000
Spain                  0.166667
Sweden                 0.200000
Ukraine                1.000000
Name: Headed goals, dtype: float64

9. Total number of fouls

In [133]:
def totalfouls (row):
    row["Fouls Won"] = (int(row["Fouls Won"]) + int(row["Fouls Conceded"]))
    return row

euro.apply(totalfouls, axis='columns').groupby("Team")["Fouls Won"].sum()

Team
Croatia                103
Czech Republic         126
Denmark                 63
England                 88
France                  87
Germany                112
Greece                 115
Italy                  190
Netherlands             65
Poland                 104
Portugal               163
Republic of Ireland     94
Russia                  77
Spain                  185
Sweden                  86
Ukraine                 79
Name: Fouls Won, dtype: int64

In [ ]:
10. How many completed Passes occured Offsides

In [137]:
def peroff (row):
    row["Offsides"] = (int(row["Offsides"]) / int(row["Passes completed"]))
    return row

euro.apply(peroff, axis='columns').groupby("Team")["Offsides"].sum()

Team
Croatia                0.002415
Czech Republic         0.006541
Denmark                0.007394
England                0.005000
France                 0.002773
Germany                0.004944
Greece                 0.013172
Italy                  0.006322
Netherlands            0.002172
Poland                 0.003521
Portugal               0.006845
Republic of Ireland    0.018152
Russia                 0.002974
Spain                  0.004974
Sweden                 0.007254
Ukraine                0.003835
Name: Offsides, dtype: float64

11. top 5 outsiders of Shooting Accuracy.

In [146]:
euro.loc[:4, ["Team", "Shooting Accuracy"]].sort_values(by="Shooting Accuracy")

             Team Shooting Accuracy
4          France             37.9%
1  Czech Republic             41.9%
2         Denmark             50.0%
3         England             50.0%
0         Croatia             51.9%

In [ ]:
12. top 3 with the best Passing Accuracy

In [145]:
euro.loc[:2, ["Team", "Passing Accuracy"]].sort_values(by="Passing Accuracy", ascending = False)

             Team Passing Accuracy
2         Denmark            83.3%
1  Czech Republic            78.1%
0         Croatia            76.9%